{"name": "Создание заказа", "status": "failed", "statusDetails": {"message": "AssertionError: assert 400 == 500\n +  where 400 = <Response [400]>.status_code", "trace": "self = <tests.test_add_order_login.TestAddOrderLogin object at 0x000001EA511D3DA0>\n\n    @allure.title('Создание заказа')\n    @allure.description('Создание заказа с неверным хешем ингридиетов')\n    def test_order_error_ingridients(self):\n        order = GetOrder()\n        response = order.add_order_error_ingridients()\n>       assert response.status_code == 500 #В документации сказано Если в запросе передан невалидный хеш ингредиента, вернётся код ответа 500Internal Server Error, почему то при проверке пишет что ошибка должна быть 400\nE       assert 400 == 500\nE        +  where 400 = <Response [400]>.status_code\n\ntests\\test_add_order_login.py:40: AssertionError"}, "description": "Создание заказа с неверным хешем ингридиетов", "start": 1717321191969, "stop": 1717321192905, "uuid": "51dde6e2-63a7-48bf-acae-dfa81849af30", "historyId": "741270a63acd6cc432e73cf16e7780eb", "testCaseId": "741270a63acd6cc432e73cf16e7780eb", "fullName": "tests.test_add_order_login.TestAddOrderLogin#test_order_error_ingridients", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_add_order_login"}, {"name": "subSuite", "value": "TestAddOrderLogin"}, {"name": "host", "value": "DESKTOP-FNOBFLJ"}, {"name": "thread", "value": "1812-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_add_order_login"}]}